FROM rockylinux:8.5 as cvm

ARG BAZEL_VERSION=5.2.0
ARG BAZEL_INSTALLER_URL=https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh

RUN yum -y install          \
    --enablerepo=powertools \
    gcc-toolset-11          \
    boost                   \
    boost-devel             \
    unzip                   \
    java-devel              \
    perl                    \
    python39                \
    unzip                   \
    which                   \
    zlib-devel

RUN python3 -m pip install pyyaml

RUN curl -o bazel-installer.sh -sSL ${BAZEL_INSTALLER_URL} \
    && chmod +x bazel-installer.sh                         \
    && ./bazel-installer.sh                                \
    && rm bazel-installer.sh                               \
    && bazel version

COPY entrypoint.sh /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["bash"]
