load("//:defs.bzl", "packet_gen", "topology_gen")
load("@rules_hdl//verilog:providers.bzl", "verilog_library")
load("@rules_verilator//verilator:defs.bzl", "verilator_cc_library")

topology_gen(
    name = "topology",
    srcs = ["topology.yml"],
    cc_attrs = {
        "alwayslink": True,
        "linkstatic": True,
    },
)

packet_gen(
    name = "transactions",
    srcs = ["shared_fields.yml", "transactions.yml"],
    topology = "topology",
    cc_attrs = {
        "alwayslink": True,
        "linkstatic": True,
    },
)

verilog_library(
    name = "defines_sv",
    srcs = ["defines.sv"],
)

verilog_library(
    name = "top",
    srcs = ["top.sv"],
    deps = [
        "defines_sv",
        "transactions_sv",
        "@cvm//:topology_sv",
        "topology_sv",
    ],
    top_module = "top",
)

verilator_cc_library(
    name = "top_veri_lib",
    module = ":top",
    vopts = [
        "--assert",
        "-Wno-DECLFILENAME",
        "+define+TB_EXTERNAL_CLOCK",
    ],
    # Disable warnings on Verilator-generated code
    copts = ["-w"],
)

cc_library(
    name = "transactions_cpp",
    deps = ["transactions_cc"],
    alwayslink = True,
    linkstatic = True,
)

cc_library(
    name = "checker",
    srcs = ["checker.cpp"],
    deps = [
        "transactions_cpp",
        "@com_google_googletest//:gtest",
        "@cvm//:topology",
        "@cvm//:registry",
        "topology_cc",
    ],
    alwayslink = True,
    linkstatic = True,
)

cc_binary(
    name = "libdpi.so",
    deps = ["checker"],
    linkshared = True,
)

cc_binary(
    name = "top_veri",
    srcs = ["sim_main.cpp"],
    deps = [
        ":checker",
        ":top_veri_lib",
        "@com_google_googletest//:gtest_main",
    ],
)

smoke_tests = []
simulator_opts = {"veri": [], "vcs": ["-licwait 1"]}
[
    [
        smoke_tests.append("smoke_{sim}_{test}".format(sim = sim, test = i)),
        sh_test(
            name = smoke_tests[-1],
            srcs = ["sim.sh"],
            args = ["$(location :top_{sim})".format(sim = sim), "+arg:{}".format(i)] + simulator_opts[sim],
            data = [":top_{sim}".format(sim = sim)],
        ),
    ]
    for i in range(1)
    for sim in ["veri"]
]

test_suite(
    name = "smoke",
    tests = smoke_tests,
)
