load("//:defs.bzl", "packet_gen")
load("@rules_hdl//verilog:providers.bzl", "verilog_library")
load("@rules_hdl//verilog:build_defs.bzl", "verilog_flist")
load("@rules_verilator//verilator:defs.bzl", "verilator_cc_library")
#load("@rules_vcs//vcs:defs.bzl", "vcs_simv")

packet_gen(
    name = "transactions",
    src  = "transactions.yml",
    cc_attrs = {
        'alwayslink': True,
        'linkstatic': True,
    }
)

verilog_library(
    name = "top",
    srcs = ["top.sv"],
    deps = ["transactions_sv"],
)

verilog_flist(
    name = "top.f",
    srcs = [":top"],
)

verilator_cc_library(
    name = "top_veri_lib",
    mtop = "top",
    vopts = [
        "-Wno-DECLFILENAME",
        "+define+TB_EXTERNAL_CLOCK",
    ],
    flist = "top.f",
)

cc_library(
    name = "transactions_cpp",
    deps = ["transactions_cc"],
    alwayslink = True,
    linkstatic = True,
)

cc_library(
    name = "checker",
    srcs = ["checker.cpp"],
    deps = [
        "transactions_cpp",
        "@com_google_googletest//:gtest",
    ],
    alwayslink = True,
    linkstatic = True,
)

cc_binary(
    name = "libdpi.so",
    deps = ["checker"],
    linkshared = True,
)

#vcs_simv(
#    name  = "top_vcs",
#    dpi   = ["libdpi.so"],
#    opts  = [
#    ],
#    flist = "top.f",
#)

cc_binary(
    name = "top_veri",
    srcs = ["sim_main.cpp"],
    deps = [
        ":checker",
        ":top_veri_lib",
        "@com_google_googletest//:gtest_main",
    ],
)

smoke_tests = []
simulator_opts = { "veri" : [], "vcs" : ["-licwait 1"] }
[
    [
        smoke_tests.append("smoke_{sim}_{test}".format(sim = sim, test = i)),
        sh_test(
            name = smoke_tests[-1],
            srcs = ["sim.sh"],
            args = ["$(location :top_{sim})".format(sim = sim), "+arg:{}".format(i),] + simulator_opts[sim],
            data = [":top_{sim}".format(sim = sim)],
        ),
    ]
    for i in range(1)
    for sim in ["veri"] #, "vcs"]

]

test_suite(
    name = "smoke",
    tests = smoke_tests,
)
