<%
    ports = spec.ports
    groups = spec.groups()
    C = "\\"
    M = spec.name.upper() + "_ATTACH"

    # A macro body cannot hold an `ifdef`, so each conditional run of ports
    # becomes its own macro, defined empty when the condition is off. A run
    # contributes in two places -- what it declares and forces, and how it
    # connects -- so it needs one of each.
    def decl_of(index):
        return "%s_%d_DECL" % (M, index)

    def conn_of(index):
        return "%s_%d_CONN" % (M, index)

    def guards(chain):
        out = []
        for cond in chain:
            out.append("`ifndef " + cond[1:] if cond.startswith("!")
                       else "`ifdef " + cond)
        return out
%>\
// Generated by src/replay/replay_gen.py -- do not edit.
// Spec: ${spec.name}   DUT: ${spec.dut}

// Attaches replay to one instance of ${spec.dut}, wherever it is. The instance
// is an argument, so this file names no design and no site: include it once and
// invoke the macro once per instance you want to replay.
//
//   `include "${spec.name}_attach.svh"
//   `${M}(alu0, top.u_chip.u_alu, LOC, rst_n, enable, done)
//
// It expands to a named generate block, so invoking it twice does not collide,
// and invoking it inside a `for (genvar ...)` attaches to an arrayed instance:
//
//   for (genvar i = 0; i < LANES; i++) begin : g_attach
//       `${M}(lane, top.u_chip.u_lane[i], LOC_OF(i), rst_n, enable, done[i])
//   end
//
// The design is not modified: the boundary is read by hierarchical reference
// and driven by force, so ${spec.dut} keeps its ports, its connections and its
// path. A forced port overrides every other driver, so the instance is
// genuinely isolated -- an inout included, which a shared net cannot manage.
//
// Every argument is prefixed, because macro substitution is textual: a plain
// `LOC` would rewrite the `.LOCATION(` formal below as well.
//
// The expansion imports what ${spec.dut}'s port types need, so a testbench
// invoking it does not have to know which packages those are.
% for index, (chain, group) in enumerate(groups):
%   if chain:

// Ports ${spec.dut} declares under ${" && ".join(chain)}.
%     for line in guards(chain):
${line}
%     endfor
`define ${decl_of(index)}(CVM_PATH) ${C}
%     for p in group:
%       if p.dir != 'out':
    ${p.sv_type()} ${p.name}_rep; ${C}
    ${p.sv_type()} ${p.name}_en; ${C}
%       endif
%     endfor
%     for p in group:
%       if p.dir == 'in':
    always @(${p.name}_en, ${p.name}_rep) begin ${C}
        if (|${p.name}_en) force CVM_PATH.${p.name} = ${p.name}_rep; ${C}
        else               release CVM_PATH.${p.name}; ${C}
    end ${C}
%       elif p.dir == 'inout':
    for (genvar b = 0; b < $bits(CVM_PATH.${p.name}); b++) begin : g_${p.name} ${C}
        always @(${p.name}_en[b], ${p.name}_rep[b]) begin ${C}
            if (${p.name}_en[b]) force CVM_PATH.${p.name}[b] = ${p.name}_rep[b]; ${C}
            else                 release CVM_PATH.${p.name}[b]; ${C}
        end ${C}
    end ${C}
%       endif
%     endfor

`define ${conn_of(index)}(CVM_PATH) ${C}
%     for p in group:
    .${p.name}_obs (CVM_PATH.${p.name}), ${C}
%       if p.dir != 'out':
    .${p.name}_rep (${p.name}_rep), ${C}
    .${p.name}_en (${p.name}_en), ${C}
%       endif
%     endfor

%     for cond in reversed(chain):
`else
`define ${decl_of(index)}(CVM_PATH)
`define ${conn_of(index)}(CVM_PATH)
`endif
%     endfor
%   endif
% endfor

`define ${M}(CVM_SITE, CVM_PATH, CVM_LOC, CVM_RESET_N, CVM_ENABLE, CVM_DONE) ${C}
    if (1) begin : CVM_SITE ${C}
% for pkg in spec.imports:
        import ${pkg}::*; ${C}
% endfor
% for index, (chain, group) in enumerate(groups):
%   if chain:
        `${decl_of(index)}(CVM_PATH) ${C}
%   else:
%     for p in group:
%       if p.dir != 'out':
        ${p.sv_type()} ${p.name}_rep; ${C}
        ${p.sv_type()} ${p.name}_en; ${C}
%       endif
%     endfor
%     for p in group:
%       if p.dir == 'in':
        always @(${p.name}_en, ${p.name}_rep) begin ${C}
            if (|${p.name}_en) force CVM_PATH.${p.name} = ${p.name}_rep; ${C}
            else               release CVM_PATH.${p.name}; ${C}
        end ${C}
%       elif p.dir == 'inout':
        for (genvar b = 0; b < $bits(CVM_PATH.${p.name}); b++) begin : g_${p.name} ${C}
            always @(${p.name}_en[b], ${p.name}_rep[b]) begin ${C}
                if (${p.name}_en[b]) force CVM_PATH.${p.name}[b] = ${p.name}_rep[b]; ${C}
                else                 release CVM_PATH.${p.name}[b]; ${C}
            end ${C}
        end ${C}
%       endif
%     endfor
%   endif
% endfor
        ${spec.name} #(.LOCATION(CVM_LOC)) u_replay ( ${C}
% for index, (chain, group) in enumerate(groups):
%   if chain:
            `${conn_of(index)}(CVM_PATH) ${C}
%   else:
%     for p in group:
            .${p.name}_obs (CVM_PATH.${p.name}), ${C}
%       if p.dir != 'out':
            .${p.name}_rep (${p.name}_rep), ${C}
            .${p.name}_en (${p.name}_en), ${C}
%       endif
%     endfor
%   endif
% endfor
            .clk (CVM_PATH.${spec.clock}), ${C}
            .reset_n (CVM_RESET_N), ${C}
            .enable (CVM_ENABLE), ${C}
            .done (CVM_DONE) ${C}
        ); ${C}
    end
