<%
    ports = spec.ports
    cursor = [0]

    def obs(p):
        """The port this module observes a signal through."""
        return p.name + "_obs"
%>\
<%def name="open_guard(chain)">\
% for cond in chain:
%   if cond.startswith('!'):
`ifndef ${cond[1:]}
%   else:
`ifdef ${cond}
%   endif
% endfor
</%def>\
<%def name="close_guard(chain)">\
% for cond in reversed(chain):
`endif
% endfor
</%def>\
// Generated by src/replay/replay_gen.py -- do not edit.
// Spec: ${spec.name}   DUT: ${spec.dut}

// Replay with no opinion about where the DUT is: the transport, the host calls,
// and the arithmetic that turns a boundary into the engine's flat vectors.
// Every port is observed through one `_obs` input, and every driveable one
// answers with `_rep` and `_en`.
//
// Nothing here names an instance, a path or a design, so one of these serves
// every ${spec.dut} anywhere. What attaches it to a particular instance is the
// macro in ${spec.name}_attach.svh, which takes the path as an argument.
module ${spec.name}
% if spec.imports:
  // In the header, not the body: these resolve the port types below.
% endif
% for pkg in spec.imports:
  import ${pkg}::*;
% endfor
#(
% for name, attrs in spec.parameters.items():
    parameter ${attrs.get('type', 'int')} ${name} = ${attrs['default']},
% endfor
    // Elements buffered in the transport. Sizes a memory, so a parameter.
    parameter int    PIPE_DEPTH = ${spec.pipe_depth},
    parameter int unsigned LOCATION = cvm_topology::nil
) (
    input  logic clk,
    // The testbench's, through the bind's port expressions: it decides when
    // replay starts and learns when it is finished.
    input  logic reset_n,
    input  logic enable,
    output logic done
% for chain, group in spec.groups():
${open_guard(chain)}\
%   for p in group:
    , input  ${p.sv_type()} ${obs(p)}
%     if p.dir != 'out':
    , output ${p.sv_type()} ${p.name}_rep
    , output ${p.sv_type()} ${p.name}_en
%     endif
%   endfor
${close_guard(chain)}\
% endfor
);

    import cvm_replay_pkg::*;

% if spec.localparams:
    // Widths ${spec.dut} keeps private, restated so the types above resolve.
${spec.localparams.rstrip()}

% endif
    // Each port's width from its own declaration, and the flat bit space they
    // tile. Offsets run through a cursor, so a port inside a conditional can
    // drop out of the chain without leaving a hole.
    localparam int CUR_0 = 0;
% for chain, group in spec.groups():
<%
    entry = cursor[0]
%>\
${open_guard(chain)}\
%   for p in group:
    localparam int W_${p.name} = $bits(${obs(p)});
    localparam int O_${p.name} = CUR_${cursor[0]};
    localparam int CUR_${cursor[0] + 1} = O_${p.name} + W_${p.name};
<%
    cursor[0] += 1
%>\
%   endfor
%   for cond in reversed(chain):
`else
    localparam int CUR_${cursor[0]} = CUR_${entry};
`endif
%   endfor
% endfor
    localparam int PORT_BITS  = CUR_${cursor[0]};
    localparam int ELEM_WORDS = 2 + 4 * ((PORT_BITS + 31) / 32);
% if spec.push_max:
    localparam int PUSH_MAX_ELEMENTS = ${spec.push_max};
% else:
    // Most elements one push may carry: what the push export's array formal holds.
    localparam int PUSH_MAX_ELEMENTS = cvm_pipe_pkg::CVM_PIPE_MAX_WORDS / ELEM_WORDS;
% endif

    logic [PORT_BITS-1:0] observed;
    logic [PORT_BITS-1:0] drive_en;
    logic [PORT_BITS-1:0] drive_val;

    // The boundary as it stands, and what to put back on it. `drive_en` is
    // already zero whenever the engine is not driving, so the interposer's
    // per-bit select needs nothing else to stay out of the way.
% for chain, group in spec.groups():
${open_guard(chain)}\
%   for p in group:
    assign observed[O_${p.name} +: W_${p.name}] = ${obs(p)};
%     if p.dir != 'out':
    assign ${p.name}_rep = drive_val[O_${p.name} +: W_${p.name}];
    assign ${p.name}_en  = drive_en [O_${p.name} +: W_${p.name}];
%     endif
%   endfor
${close_guard(chain)}\
% endfor

    // Sourcing the recording is this module's job, not the engine's: the engine
    // consumes elements and knows nothing of files or layouts. Once, out of
    // reset. Bound port by port rather than through one formatted string,
    // because the widths are parameters here.
    logic loaded;
    always_ff @(posedge clk) begin
        if (!reset_n) begin
            loaded <= 1'b0;
        end else if (!loaded) begin
            loaded <= 1'b1;
% for chain, group in spec.groups():
${open_guard(chain)}\
%   for p in group:
            void'(cvm_replay_bind(LOCATION, "${p.dump_name}", W_${p.name}, O_${p.name}, ${p.dir_code()}));
%   endfor
${close_guard(chain)}\
% endfor
            // Carried by the recording and deliberately not replayed.
% for name in spec.ignored():
            void'(cvm_replay_ignore(LOCATION, "${name}"));
% endfor
            if (cvm_replay_load(LOCATION, PORT_BITS, ELEM_WORDS) < 0)
                $error("%m: could not load the recording");
        end
    end

    cvm_replay_engine #(
        .PORT_BITS         (PORT_BITS),
        .PIPE_DEPTH        (PIPE_DEPTH),
        .LOCATION          (LOCATION),
        .PUSH_MAX_ELEMENTS (PUSH_MAX_ELEMENTS)
    ) u_engine (
        .clk              (clk),
        .reset_n          (reset_n),
        .enable           (enable),
        .done             (done),
        .observed         (observed),
        // The interposer does the muxing, so the engine's own bypass output is
        // unused here: `drive_val` is the recorded stimulus with no fallback.
        .driven           (),
        .drive_en         (drive_en),
        .drive_val        (drive_val),
        .mismatches       (),
        .first_fail_cycle (),
        .fail_bits        ()
    );

endmodule
