<%
    ports = spec.ports
    tb = spec.tb_suffix
    du = spec.dut_suffix
    groups = spec.groups()
    # A literal backslash-newline: Mako treats a trailing backslash as its own
    # line continuation, so the one SystemVerilog needs has to be emitted.
    C = "\\"

    def side(p):
        if p.dir == 'inout':
            return p.name
        return p.name + (tb if p.dir == 'in' else du)

    # A macro body cannot hold an `ifdef`, so each conditional run of ports
    # becomes its own macro, defined empty when the condition is off.
    def helper(index):
        return "%s_BIND_%d" % (spec.replay_define, index)
%>\
// Generated by src/replay/replay_gen.py -- do not edit.
// Spec: ${spec.name}   DUT: ${spec.dut}
//
// The bind a testbench performs to put replay inside ${spec.name}. Include this
// and invoke the macro with the testbench's own signals:
//
//   `include "${spec.name}_bind.svh"
//   `${spec.replay_define}_BIND(
//       cvm_topology_gen::get_location(topo.TOP.REPLAY.ID, 0),
//       tb_reset_n, tb_enable, tb_done)
//
// The bind is what lets the testbench own all four of those: a bind takes
// parameters and ports, where nothing reaching into a hierarchy can.
% for index, (chain, group) in enumerate(groups):
%   if chain:

// Ports ${spec.dut} declares under ${" && ".join(chain)}, so the connections
// appear only when they do.
%     for cond in chain:
%       if cond.startswith('!'):
`ifndef ${cond[1:]}
%       else:
`ifdef ${cond}
%       endif
%     endfor
`define ${helper(index)} ${C}
%     for p in group:
%       if p.dir == 'out':
    .${p.name}${du}(${p.name}${du}), ${C}
%       else:
    .${side(p)}(${side(p)}), ${C}
    .${p.name}_rep(${p.name}_rep), ${C}
    .${p.name}_en(${p.name}_en), ${C}
%       endif
%     endfor

%     for cond in reversed(chain):
`else
`define ${helper(index)}
`endif
%     endfor
%   endif
% endfor

// The boundary first and the four control connections last, so nothing has to
// absorb a trailing comma.
`define ${spec.replay_define}_BIND(LOCATION_EXPR, RESET_N, ENABLE, DONE) ${C}
    bind ${spec.name} ${spec.name}_bound #(.LOCATION(LOCATION_EXPR)) u_cvm_replay ( ${C}
% for index, (chain, group) in enumerate(groups):
%   if chain:
        `${helper(index)} ${C}
%   else:
%     for p in group:
%       if p.dir == 'out':
        .${p.name}${du}(${p.name}${du}), ${C}
%       else:
        .${side(p)}(${side(p)}), ${C}
        .${p.name}_rep(${p.name}_rep), ${C}
        .${p.name}_en(${p.name}_en), ${C}
%       endif
%     endfor
%   endif
% endfor
        .clk(${spec.clock}), ${C}
        .reset_n(RESET_N), ${C}
        .enable(ENABLE), ${C}
        .done(DONE) ${C}
    );
