<%
    ports = spec.ports
    P = spec.instance_path
%>\
<%def name="open_guard(chain)">\
% for cond in chain:
%   if cond.startswith('!'):
`ifndef ${cond[1:]}
%   else:
`ifdef ${cond}
%   endif
% endfor
</%def>\
<%def name="close_guard(chain)">\
% for cond in reversed(chain):
`endif
% endfor
</%def>\
// Generated by src/replay/replay_gen.py -- do not edit.
// Spec: ${spec.name}   DUT: ${spec.dut}   Instance: ${P}

// Replays ${P} where it stands, with no change to the design that contains it:
// the boundary is read by hierarchical reference and driven by force, so the
// DUT keeps its ports, its connections and its path, and nothing has to be
// interposed or re-elaborated.
//
// A forced port overrides every other driver, so the block is genuinely
// isolated for the bits the recording drives -- including an inout, where a
// shared net cannot be. `release` hands each one back, and the design's own
// driver takes it on its next evaluation.
//
// The path cannot be a parameter -- SystemVerilog has no way to build a
// hierarchical name from one -- so it is generated in, and this module is
// therefore one per replayed instance.
module ${spec.name}
% if spec.imports:
  // The port types below come from these, as they do in ${spec.dut}.
% endif
% for pkg in spec.imports:
  import ${pkg}::*;
% endfor
#(
% for name, attrs in spec.parameters.items():
    parameter ${attrs.get('type', 'int')} ${name} = ${attrs['default']},
% endfor
    // Elements buffered in the transport. Sizes a memory, so a parameter.
    parameter int    PIPE_DEPTH = ${spec.pipe_depth},
    parameter int unsigned LOCATION = cvm_topology::nil
) (
    input  logic clk,
    input  logic reset_n,
    input  logic enable,
    output logic done
);

    // What the engine wants driven, per port. Held here rather than forced
    // straight from the instance so the force statements stay one line each.
% for chain, group in spec.groups():
${open_guard(chain)}\
%   for p in group:
%     if p.dir != 'out':
    ${p.sv_type()} ${p.name}_rep;
    ${p.sv_type()} ${p.name}_en;
%     endif
%   endfor
${close_guard(chain)}\
% endfor

    ${spec.name}_bound #(
% for name in spec.parameters:
        .${name} (${name}),
% endfor
        .PIPE_DEPTH (PIPE_DEPTH),
        .LOCATION   (LOCATION)
    ) u_bound (
        .clk     (clk),
        .reset_n (reset_n),
        .enable  (enable),
        .done    (done)
% for chain, group in spec.groups():
${open_guard(chain)}\
%   for p in group:
        // Read where it is. An input reads back the forced value, which costs
        // nothing: an input is never compared.
        , .${p.name}_obs (${P}.${p.name})
%     if p.dir != 'out':
        , .${p.name}_rep (${p.name}_rep)
        , .${p.name}_en  (${p.name}_en)
%     endif
%   endfor
${close_guard(chain)}\
% endfor
    );

    // Combinational, not clocked: the engine presents the cycle's stimulus just
    // after an edge, and the DUT samples it at the next one. Forcing on the
    // edge would land a cycle late and shift the whole replay.
    //
    // The sensitivity is written out rather than `@(*)`, which reads the forced
    // signal back into the block's own sensitivity and makes every port look
    // like a combinational loop.
    //
    // An input's enable is all of it or none, so one force covers the port. An
    // inout's varies bit by bit, because the recording says which side had
    // each one, so it is forced and released a bit at a time.
% for chain, group in spec.groups():
${open_guard(chain)}\
%   for p in group:
%     if p.dir == 'in':
    always @(${p.name}_en, ${p.name}_rep) begin
        if (|${p.name}_en) force ${P}.${p.name} = ${p.name}_rep;
        else               release ${P}.${p.name};
    end
%     endif
%   endfor
${close_guard(chain)}\
% endfor
% for chain, group in spec.groups():
${open_guard(chain)}\
%   for p in group:
%     if p.dir == 'inout':

    for (genvar b = 0; b < $bits(${P}.${p.name}); b++) begin : g_${p.name}
        always @(${p.name}_en[b], ${p.name}_rep[b]) begin
            if (${p.name}_en[b]) force ${P}.${p.name}[b] = ${p.name}_rep[b];
            else                 release ${P}.${p.name}[b];
        end
    end
%     endif
%   endfor
${close_guard(chain)}\
% endfor

endmodule
