<%
    ports = spec.ports
    outer = spec.outer_suffix
    inner = spec.inner_suffix
%>\
<%def name="open_guard(chain)">\
% for cond in chain:
%   if cond.startswith('!'):
`ifndef ${cond[1:]}
%   else:
`ifdef ${cond}
%   endif
% endfor
</%def>\
<%def name="close_guard(chain)">\
% for cond in reversed(chain):
`endif
% endfor
</%def>\
// Generated by src/replay/replay_gen.py -- do not edit.
// Spec: ${spec.name}   DUT: ${spec.dut}

// Sits beside ${spec.dut} rather than around it, so ${spec.dut}'s instance keeps
// its name and its hierarchical path -- which is what every waveform script,
// coverage database and constraint file in the design depends on.
//
// Synthesized as well as simulated, so there is nothing of replay in here: no
// DPI, no transport, no cvm package. Just the connections, and the signals a
// bound module drives to take the boundary over. With REPLAY_ENABLE = 0 the
// whole thing is wires.
`ifdef ${spec.replay_define}
  `define ${spec.replay_define}_ON 1
`else
  `define ${spec.replay_define}_ON 0
`endif

module ${spec.name}
% if spec.imports:
  // In the header, not the body: these resolve the port types below, and a
  // body import comes too late for a port declaration.
% endif
% for pkg in spec.imports:
  import ${pkg}::*;
% endfor
#(
% for name, attrs in spec.parameters.items():
    parameter ${attrs.get('type', 'int')} ${name} = ${attrs['default']},
% endfor
    // The one thing a define decides; everything below follows from it. A
    // parent may override it per instance to replay one site of several.
    parameter bit REPLAY_ENABLE = `${spec.replay_define}_ON
) (
    // The DUT's clock, so a bound module can take it from here rather than
    // reaching for it. Never replayed: a cycle-indexed recording samples once
    // per cycle, so a clock reads as a constant in one.
    input  logic ${spec.clock}
% for chain, group in spec.groups():
${open_guard(chain)}\
%   for p in group:
%     if p.dir == 'in':
    , input  ${p.sv_type()} ${p.name}${outer}
    , output ${p.sv_type()} ${p.name}${inner}
%     elif p.dir == 'out':
    , input  ${p.sv_type()} ${p.name}${inner}
    , output ${p.sv_type()} ${p.name}${outer}
%     else:
    // One port, because an inout is one net: the parent leaves ${p.name}
    // connected to ${spec.dut} as it was, and this taps the same net.
    , inout  ${p.sv_type()} ${p.name}
%     endif
%   endfor
${close_guard(chain)}\
% endfor
);

    // What a bound module drives to take a bit over. `_en` selects per bit, so
    // one mechanism serves an input and an inout alike, and nothing here needs
    // to know which cycle replay starts on. Unwritten and unread when
    // REPLAY_ENABLE is 0, so synthesis drops them.
% for chain, group in spec.groups():
${open_guard(chain)}\
%   for p in group:
%     if p.dir != 'out':
    ${p.sv_type()} ${p.name}_rep;
    ${p.sv_type()} ${p.name}_en;
%     endif
%   endfor
${close_guard(chain)}\
% endfor

    // ${spec.dut}'s outputs pass straight through either way: replay reads them,
    // it never drives them.
% for chain, group in spec.groups():
${open_guard(chain)}\
%   for p in group:
%     if p.dir == 'out':
    assign ${p.name}${outer} = ${p.name}${inner};
%     endif
%   endfor
${close_guard(chain)}\
% endfor

    if (REPLAY_ENABLE) begin : g_replay
% for chain, group in spec.groups():
${open_guard(chain)}\
%   for p in group:
%     if p.dir == 'in':
        assign ${p.name}${inner} =
            (${p.name}_rep & ${p.name}_en) | (${p.name}${outer} & ~${p.name}_en);
%     elif p.dir == 'inout':
        for (genvar b = 0; b < $bits(${p.name}); b++) begin : g_${p.name}
            assign ${p.name}[b] = ${p.name}_en[b] ? ${p.name}_rep[b] : 1'bz;
        end
%     endif
%   endfor
${close_guard(chain)}\
% endfor
    end else begin : g_direct
% for chain, group in spec.groups():
${open_guard(chain)}\
%   for p in group:
%     if p.dir == 'in':
        assign ${p.name}${inner} = ${p.name}${outer};
%     endif
%   endfor
${close_guard(chain)}\
% endfor
    end

endmodule
