<%
    ports = spec.ports
    tb = spec.tb_suffix
    du = spec.dut_suffix
%>\
// Generated by src/replay/replay_gen.py -- do not edit.
// Spec: ${spec.name}   DUT: ${spec.dut}

// Interposer: the DUT's IO flows through it, so every port appears on both
// sides -- the testbench connects `*${tb}`, the DUT connects `*${du}`. This
// file only packs the boundary into the flat vectors cvm_replay_engine works
// in; the behaviour is all there.
//
// Widths are never resolved here. Each port is declared with the DUT's own
// type and measured with $bits, so a width that depends on a parameter or a
// package constant stays parametric and this module holds for every
// configuration of ${spec.dut}.
module ${spec.name}
% for pkg in spec.imports:
  // In the header, not the body: these resolve the port types below, and a
  // body import comes too late for a port declaration.
  import ${pkg}::*;
% endfor
#(
% for name, attrs in spec.parameters.items():
    parameter ${attrs.get('type', 'int')} ${name} = ${attrs['default']},
% endfor
    // Elements buffered in the transport. Sizes a memory, so a parameter.
    parameter int    PIPE_DEPTH = ${spec.pipe_depth},
    parameter int unsigned LOCATION = cvm_topology::nil
) (
    // Infrastructure, not a replayed port: a cycle-indexed recording samples
    // once per cycle, so the DUT's clock reads as a constant in it.
    input  logic clk,
    input  logic reset_n,
    input  logic enable,
    output logic done,
% for p in ports:
%   if p.dir == 'in':
    input  ${p.sv_type()} ${p.name}${tb},
    output ${p.sv_type()} ${p.name}${du}${'' if loop.last else ','}
%   else:
    input  ${p.sv_type()} ${p.name}${du},
    output ${p.sv_type()} ${p.name}${tb}${'' if loop.last else ','}
%   endif
% endfor
);

    import cvm_replay_pkg::*;

% if spec.localparams:
    // Widths ${spec.dut} keeps private, restated so the types above resolve.
${spec.localparams.rstrip()}

% endif
    // Each port's width from its own declaration, and the flat bit space they
    // tile. All elaboration-time constants, so the part-selects below are legal
    // however a width was spelled.
<%
    prev = None
%>\
% for p in ports:
    localparam int W_${p.name} = $bits(${p.name}${tb if p.dir == 'in' else du});
%   if prev is None:
    localparam int O_${p.name} = 0;
%   else:
    localparam int O_${p.name} = O_${prev.name} + W_${prev.name};
%   endif
<%
    prev = p
%>\
% endfor
    localparam int PORT_BITS  = O_${ports[-1].name} + W_${ports[-1].name};
    localparam int ELEM_WORDS = 2 + 3 * ((PORT_BITS + 31) / 32);
% if spec.push_max:
    localparam int PUSH_MAX_ELEMENTS = ${spec.push_max};
% else:
    // Most elements one push may carry: what the push export's array formal holds.
    localparam int PUSH_MAX_ELEMENTS = cvm_pipe_pkg::CVM_PIPE_MAX_WORDS / ELEM_WORDS;
% endif

    logic [PORT_BITS-1:0] observed;
    logic [PORT_BITS-1:0] driven;

    // The DUT boundary as it stands: the testbench's value on each input slice,
    // the DUT's value on each output slice.
% for p in ports:
    assign observed[O_${p.name} +: W_${p.name}] = ${p.name}${tb if p.dir == 'in' else du};
% endfor

    // DUT inputs come from the engine, which muxes between the recording and
    // the testbench side. Exactly one driver each.
% for p in spec.inputs():
    assign ${p.name}${du} = driven[O_${p.name} +: W_${p.name}];
% endfor

    // DUT outputs pass straight through in both modes.
% for p in spec.outputs():
    assign ${p.name}${tb} = ${p.name}${du};
% endfor

    // Sourcing the recording is the interposer's job, not the engine's: the
    // engine consumes elements and knows nothing of files or layouts, which is
    // what lets it be driven by a generator instead. Once, out of reset.
    //
    // Bound port by port rather than through one formatted string, because the
    // widths are parameters here and a string would have to be built at
    // elaboration.
    logic loaded;
    always_ff @(posedge clk) begin
        if (!reset_n) begin
            loaded <= 1'b0;
        end else if (!loaded) begin
            loaded <= 1'b1;
% for p in ports:
            void'(cvm_replay_bind(LOCATION, "${p.dump_name}", W_${p.name}, O_${p.name}, ${1 if p.dir == 'out' else 0}));
% endfor
            if (cvm_replay_load(LOCATION, PORT_BITS, ELEM_WORDS) < 0)
                $error("%m: could not load the recording");
        end
    end

    cvm_replay_engine #(
        .PORT_BITS          (PORT_BITS),
        .PIPE_DEPTH         (PIPE_DEPTH),
        .LOCATION           (LOCATION),
        .PUSH_MAX_ELEMENTS (PUSH_MAX_ELEMENTS)
    ) u_engine (
        .clk              (clk),
        .reset_n          (reset_n),
        .enable           (enable),
        .done             (done),
        .observed         (observed),
        .driven           (driven),
        .mismatches       (),
        .first_fail_cycle (),
        .fail_bits        ()
    );

endmodule
% if spec.standalone_top:

// Convenience top for standalone block regression. An integrated testbench
// should instantiate ${spec.name} itself.
module ${spec.name}_top (
    input  logic clk,
    input  logic reset_n,
    input  logic enable,
    output logic done
);

% for pkg in spec.imports:
    import ${pkg}::*;
% endfor
% for p in ports:
    ${p.sv_type()} ${p.name}${tb};
    ${p.sv_type()} ${p.name}${du};
% endfor

    ${spec.name} u_replay (
        .clk(clk),
        .reset_n(reset_n),
        .enable(enable),
        .done(done),
% for p in ports:
        .${p.name}${tb}(${p.name}${tb}),
        .${p.name}${du}(${p.name}${du})${'' if loop.last else ','}
% endfor
    );

    ${spec.dut} u_dut (
        .${spec.clock}(clk),
% for p in ports:
        .${p.name}(${p.name}${du})${'' if loop.last else ','}
% endfor
    );

endmodule
% endif
