<%
    ports = spec.ports
    tb = spec.tb_suffix
    du = spec.dut_suffix
    cursor = [0]
%>\
<%def name="open_guard(chain)">\
% for cond in chain:
`ifdef ${cond}
% endfor
</%def>\
<%def name="close_guard(chain)">\
% for cond in reversed(chain):
`endif
% endfor
</%def>\
// Generated by src/replay/replay_gen.py -- do not edit.
// Spec: ${spec.name}   DUT: ${spec.dut}

// Interposer: the DUT's IO flows through it, so every port appears on both
// sides -- the testbench connects `*${tb}`, the DUT connects `*${du}`. This
// file only packs the boundary into the flat vectors cvm_replay_engine works
// in; the behaviour is all there.
//
// Nothing here is resolved at generation time that SystemVerilog can resolve at
// elaboration. Each port is declared with the DUT's own type and measured with
// $bits, and a conditional port carries the DUT's own `ifdef`s -- so this
// module holds for every parameterization and every define setting of
// ${spec.dut}, from one generated file.
module ${spec.name}
% for pkg in spec.imports:
  // In the header, not the body: these resolve the port types below, and a
  // body import comes too late for a port declaration.
  import ${pkg}::*;
% endfor
#(
% for name, attrs in spec.parameters.items():
    parameter ${attrs.get('type', 'int')} ${name} = ${attrs['default']},
% endfor
    // Elements buffered in the transport. Sizes a memory, so a parameter.
    parameter int    PIPE_DEPTH = ${spec.pipe_depth},
    parameter int unsigned LOCATION = cvm_topology::nil
) (
    // Infrastructure, not a replayed port: a cycle-indexed recording samples
    // once per cycle, so the DUT's clock reads as a constant in it.
    input  logic clk,
    input  logic reset_n,
    input  logic enable,
    output logic done
    // Leading commas from here on, so a conditional port needs no say in
    // whether it is the last one in the list.
% for chain, group in spec.groups():
${open_guard(chain)}\
%   for p in group:
%     if p.dir == 'in':
    , input  ${p.sv_type()} ${p.name}${tb}
    , output ${p.sv_type()} ${p.name}${du}
%     else:
    , input  ${p.sv_type()} ${p.name}${du}
    , output ${p.sv_type()} ${p.name}${tb}
%     endif
%   endfor
${close_guard(chain)}\
% endfor
);

    import cvm_replay_pkg::*;

% if spec.localparams:
    // Widths ${spec.dut} keeps private, restated so the types above resolve.
${spec.localparams.rstrip()}

% endif
    // Each port's width from its own declaration, and the flat bit space they
    // tile. All elaboration-time constants, so the part-selects below are legal
    // however a width was spelled.
    //
    // Offsets run through a cursor rather than naming the previous port,
    // because a port can sit inside a conditional: an absent one passes the
    // cursor through untouched, where naming it would leave a hole in the chain.
    localparam int CUR_0 = 0;
% for chain, group in spec.groups():
<%
    entry = cursor[0]
%>\
${open_guard(chain)}\
%   for p in group:
    localparam int W_${p.name} = $bits(${p.name}${tb if p.dir == 'in' else du});
    localparam int O_${p.name} = CUR_${cursor[0]};
    localparam int CUR_${cursor[0] + 1} = O_${p.name} + W_${p.name};
<%
    cursor[0] += 1
%>\
%   endfor
%   for cond in reversed(chain):
`else
    localparam int CUR_${cursor[0]} = CUR_${entry};
`endif
%   endfor
% endfor
    localparam int PORT_BITS  = CUR_${cursor[0]};
    localparam int ELEM_WORDS = 2 + 3 * ((PORT_BITS + 31) / 32);
% if spec.push_max:
    localparam int PUSH_MAX_ELEMENTS = ${spec.push_max};
% else:
    // Most elements one push may carry: what the push export's array formal holds.
    localparam int PUSH_MAX_ELEMENTS = cvm_pipe_pkg::CVM_PIPE_MAX_WORDS / ELEM_WORDS;
% endif

    logic [PORT_BITS-1:0] observed;
    logic [PORT_BITS-1:0] driven;

    // The DUT boundary as it stands: the testbench's value on each input slice,
    // the DUT's value on each output slice. DUT inputs then come from the
    // engine, which muxes between the recording and the testbench side, and
    // DUT outputs pass straight through in both modes.
% for chain, group in spec.groups():
${open_guard(chain)}\
%   for p in group:
    assign observed[O_${p.name} +: W_${p.name}] = ${p.name}${tb if p.dir == 'in' else du};
%     if p.dir == 'in':
    assign ${p.name}${du} = driven[O_${p.name} +: W_${p.name}];
%     else:
    assign ${p.name}${tb} = ${p.name}${du};
%     endif
%   endfor
${close_guard(chain)}\
% endfor

    // Sourcing the recording is the interposer's job, not the engine's: the
    // engine consumes elements and knows nothing of files or layouts, which is
    // what lets it be driven by a generator instead. Once, out of reset.
    //
    // Bound port by port rather than through one formatted string, because the
    // widths are parameters here and a string would have to be built at
    // elaboration.
    logic loaded;
    always_ff @(posedge clk) begin
        if (!reset_n) begin
            loaded <= 1'b0;
        end else if (!loaded) begin
            loaded <= 1'b1;
% for chain, group in spec.groups():
${open_guard(chain)}\
%   for p in group:
            void'(cvm_replay_bind(LOCATION, "${p.dump_name}", W_${p.name}, O_${p.name}, ${1 if p.dir == 'out' else 0}));
%   endfor
${close_guard(chain)}\
% endfor
            if (cvm_replay_load(LOCATION, PORT_BITS, ELEM_WORDS) < 0)
                $error("%m: could not load the recording");
        end
    end

    cvm_replay_engine #(
        .PORT_BITS          (PORT_BITS),
        .PIPE_DEPTH         (PIPE_DEPTH),
        .LOCATION           (LOCATION),
        .PUSH_MAX_ELEMENTS (PUSH_MAX_ELEMENTS)
    ) u_engine (
        .clk              (clk),
        .reset_n          (reset_n),
        .enable           (enable),
        .done             (done),
        .observed         (observed),
        .driven           (driven),
        .mismatches       (),
        .first_fail_cycle (),
        .fail_bits        ()
    );

endmodule
% if spec.standalone_top:

// Convenience top for standalone block regression. An integrated testbench
// should instantiate ${spec.name} itself.
module ${spec.name}_top (
    input  logic clk,
    input  logic reset_n,
    input  logic enable,
    output logic done
);

% for pkg in spec.imports:
    import ${pkg}::*;
% endfor
% for chain, group in spec.groups():
${open_guard(chain)}\
%   for p in group:
    ${p.sv_type()} ${p.name}${tb};
    ${p.sv_type()} ${p.name}${du};
%   endfor
${close_guard(chain)}\
% endfor

    ${spec.name} u_replay (
        .clk(clk),
        .reset_n(reset_n),
        .enable(enable),
        .done(done)
% for chain, group in spec.groups():
${open_guard(chain)}\
%   for p in group:
        , .${p.name}${tb}(${p.name}${tb})
        , .${p.name}${du}(${p.name}${du})
%   endfor
${close_guard(chain)}\
% endfor
    );

    ${spec.dut} u_dut (
        .${spec.clock}(clk)
% for chain, group in spec.groups():
${open_guard(chain)}\
%   for p in group:
        , .${p.name}(${p.name}${du})
%   endfor
${close_guard(chain)}\
% endfor
    );

endmodule
% endif
