include:
  - local: 'infra/container/gitlab-container.yml'
  - project: 'riscv/dv/gitlab-definitions'
    ref: main
    file: 'common-definitions.yml'

stages:
    - test
    - notify

test:
    stage: test
    extends:
        - .smoke-rules-all-branches-template
    script:
        - bazel --output_user_root=./bazel_output_user_root test //test/... --test_output=all
    after_script:
        - chmod +w -R ./bazel_output_user_root

test-bazel7:
    stage: test
    extends:
        - .smoke-rules-all-branches-template
    script:
        - bazel-7 --output_user_root=./bazel_output_user_root test //test/... --test_output=all --enable_bzlmod
    after_script:
        - chmod +w -R ./bazel_output_user_root

notify_rv_tester:
    stage: notify
    extends:
        - .notify-template
    trigger:
        project: riscv/dv/rv_tester

# https://tenstorrent.atlassian.net/wiki/spaces/RVRTLDV/pages/1421574263/Ascalon+-+Dependency+Freeze+Plan
notify_rv_tester_asc_release:
    stage: notify
    rules:
        - if: '$CI_COMMIT_BRANCH =~ /^ascalon\/ea\/a0/ && $CI_PIPELINE_SOURCE == "push"'
    extends:
        - .notify-template
    trigger:
        project: riscv/dv/rv_tester
        branch: ascalon/ea/a0
    variables:
        UPDATE_TARGET_BRANCH: ascalon/ea/a0

