load("@rules_hdl//verilog:providers.bzl", "verilog_library")

cc_library(
    name = "logger",
    hdrs = ["logger.hpp"],
    srcs = ["logger.cpp"],
    deps = [
        "@fmt//:fmt",
        "//:plusargs",
    ],
    strip_include_prefix = ".",
    include_prefix = "cvm",
    visibility = ["//:__pkg__"],
)

verilog_library(
  name = "logger_sv",
  srcs = ["cvm_logger.sv"],
  visibility = ["//:__pkg__"],
)
