// SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
// SPDX-License-Identifier: Apache-2.0

// Generated by src/topology/topology_gen.py. Do not edit.

// The topology tables live in the generated cvm::static_topology; this unit
// only adapts them to the runtime cvm::topology signatures, so a translation
// unit that cannot resolve its lookups at compile time still links against the
// same data.

#include <string>
#include <utility>
#include <vector>

#include "cvm/topology.hpp"
#include "cvm/topology_defs.hpp"

namespace cvm {
  namespace topology {

    std::vector<loc_t> get_from_type(const std::string& type) {
      const auto locations = cvm::static_topology::get_from_type(type);
      return std::vector<loc_t>(locations.begin(), locations.end());
    }

    std::vector<loc_t> get_from_hierarchy(const std::string& hierarchy) {
      const auto locations = cvm::static_topology::get_from_hierarchy(hierarchy);
      return std::vector<loc_t>(locations.begin(), locations.end());
    }

    loc_t get_from_type(const std::string& type, unsigned id) {
      return cvm::static_topology::get_from_type(type, id);
    }

    loc_t get_from_hierarchy(const std::string& hierarchy, unsigned id) {
      return cvm::static_topology::get_from_hierarchy(hierarchy, id);
    }

    std::pair<bool, uint32_t> attr(loc_t loc, const std::string& attribute) {
      const auto value = cvm::static_topology::attr(loc, attribute);

      if (not value)
        return std::make_pair(false, uint32_t(0));

      return std::make_pair(true, *value);
    }

    std::pair<bool, std::vector<uint32_t>> list_attr(loc_t loc, const std::string& attribute) {
      const auto values = cvm::static_topology::list_attr(loc, attribute);

      if (not values)
        return std::make_pair(false, std::vector<uint32_t>{});

      return std::make_pair(true, std::vector<uint32_t>(values->begin(), values->end()));
    }

    std::string name(loc_t loc) {
      return std::string(cvm::static_topology::name(loc));
    }
  }
}
