<%
  t = topo.constexpr_tables()

  def sv(s):
    return '"' + str(s).replace('\\', '\\\\').replace('"', '\\"') + '"'

  def scalars(values, per_line = 12):
    if not values:
      return "{}"
    rows = [values[i:i + per_line] for i in range(0, len(values), per_line)]
    body = "\n".join("        " + ", ".join(str(v) for v in row) + "," for row in rows)
    return "{\n" + body + "\n      }"

  def records(rows):
    if not rows:
      return "{}"
    body = "\n".join("        {" + ", ".join(row) + "}," for row in rows)
    return "{{\n" + body + "\n      }}"
%>\
// SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
// SPDX-License-Identifier: Apache-2.0

// Generated by src/topology/topology_gen.py. Do not edit.

#pragma once

#include <algorithm>
#include <array>
#include <cstddef>
#include <cstdint>
#include <optional>
#include <span>
#include <string_view>

#include "cvm/location_defs.hpp"

namespace cvm {

  class static_topology {

    public:

      using loc_t = cvm::location_defs::loc_t;

      static constexpr loc_t null = cvm::location_defs::null;

      struct range_entry {
        std::string_view key;
        uint32_t begin;
        uint32_t count;
      };

      struct attribute_entry {
        loc_t loc;
        std::string_view key;
        uint32_t value;
      };

      struct list_entry {
        loc_t loc;
        std::string_view key;
        uint32_t begin;
        uint32_t count;
      };

    private:

      static constexpr std::array<loc_t, ${len(t["type_pool"])}> type_pool_ = ${scalars(t["type_pool"])};

      static constexpr std::array<range_entry, ${len(t["type_index"])}> type_index_ = ${records([(sv(k), str(b), str(c)) for k, b, c in t["type_index"]])};

      static constexpr std::array<loc_t, ${len(t["hierarchy_pool"])}> hierarchy_pool_ = ${scalars(t["hierarchy_pool"])};

      static constexpr std::array<range_entry, ${len(t["hierarchy_index"])}> hierarchy_index_ = ${records([(sv(k), str(b), str(c)) for k, b, c in t["hierarchy_index"]])};

      static constexpr std::array<attribute_entry, ${len(t["attributes"])}> attribute_index_ = ${records([(str(l), sv(k), str(v)) for l, k, v in t["attributes"]])};

      static constexpr std::array<uint32_t, ${len(t["list_pool"])}> list_pool_ = ${scalars(t["list_pool"])};

      static constexpr std::array<list_entry, ${len(t["list_index"])}> list_index_ = ${records([(str(l), sv(k), str(b), str(c)) for l, k, b, c in t["list_index"]])};

      static constexpr std::array<std::string_view, ${len(t["names"])}> names_ = ${scalars([sv(n) for n in t["names"]], 8)};

      template <typename Index, typename Pool>
      static constexpr std::span<const typename Pool::value_type>
      find_range(const Index& index, const Pool& pool, std::string_view key) {
        const auto found = std::lower_bound(
            index.begin(), index.end(), key,
            [](const range_entry& entry, std::string_view probe) { return entry.key < probe; });

        if (found == index.end() or found->key != key)
          return {};

        return std::span<const typename Pool::value_type>(pool.data() + found->begin, found->count);
      }

      template <typename Index>
      static constexpr auto find_attribute(const Index& index, loc_t loc, std::string_view key) {
        const auto found = std::lower_bound(
            index.begin(), index.end(), key,
            [loc](const auto& entry, std::string_view probe) {
              return entry.loc != loc ? entry.loc < loc : entry.key < probe;
            });

        return (found == index.end() or found->loc != loc or found->key != key)
                 ? index.end()
                 : found;
      }

    public:

      static constexpr std::span<const loc_t> locations_of_type(std::string_view type) {
        return find_range(type_index_, type_pool_, type);
      }

      static constexpr loc_t location_of_type(std::string_view type, unsigned id) {
        const auto locations = locations_of_type(type);
        return id < locations.size() ? locations[id] : null;
      }

      static constexpr bool type_exists(std::string_view type) {
        return not locations_of_type(type).empty();
      }

      static constexpr std::span<const loc_t> locations_of_hierarchy(std::string_view hierarchy) {
        return find_range(hierarchy_index_, hierarchy_pool_, hierarchy);
      }

      static constexpr loc_t location_of_hierarchy(std::string_view hierarchy, unsigned id) {
        const auto locations = locations_of_hierarchy(hierarchy);
        return id < locations.size() ? locations[id] : null;
      }

      static constexpr bool hierarchy_exists(std::string_view hierarchy) {
        return not locations_of_hierarchy(hierarchy).empty();
      }

      static constexpr std::optional<uint32_t> attribute(loc_t loc, std::string_view key) {
        const auto found = find_attribute(attribute_index_, loc, key);
        if (found == attribute_index_.end())
          return std::nullopt;
        return found->value;
      }

      static constexpr std::optional<std::span<const uint32_t>>
      list_attribute(loc_t loc, std::string_view key) {
        const auto found = find_attribute(list_index_, loc, key);
        if (found == list_index_.end())
          return std::nullopt;
        return std::span<const uint32_t>(list_pool_.data() + found->begin, found->count);
      }

      static constexpr std::string_view name(loc_t loc) {
        return loc < names_.size() ? names_[loc] : std::string_view{};
      }

      static constexpr std::span<const range_entry> types() { return std::span(type_index_); }

      static constexpr std::span<const range_entry> hierarchies() { return std::span(hierarchy_index_); }

      static constexpr std::span<const attribute_entry> attributes() { return std::span(attribute_index_); }

      static constexpr std::span<const list_entry> list_attributes() { return std::span(list_index_); }

      static constexpr std::span<const std::string_view> names() { return std::span(names_); }
  };
}
