load("@rules_hdl//verilog:providers.bzl", "verilog_library")
load("@rules_verilator//verilator:defs.bzl", "verilator_cc_library")

verilog_library(
    name = "plusargs_test_sv",
    srcs = ["plusargs_test.sv"],
    deps = ["//:plusargs_sv"],
    top_module = "plusargs_test",
)

verilator_cc_library(
    name = "plusargs_test_veri_lib",
    module = ":plusargs_test_sv",
    vopts = ["--assert"],
)

cc_binary(
    name = "plusargs_test",
    srcs = ["plusargs_test.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//:plusargs",
        ":plusargs_test_veri_lib",
    ],
)

sh_test(
    name = "sh_plusargs_test",
    srcs = ["sim.sh"],
    args = ["$(location :plusargs_test)"],
    data = [":plusargs_test"],
)
