cc_library(
  name = "registry",
  hdrs = ["registry.hpp"],
  deps = [
      "@cvm//:messenger",
      "@cvm//:callbacks",
      "@cvm//:topology",
      "@cvm//:remote_procedure_call",
  ],
  strip_include_prefix = "//src/registry",
  include_prefix = "cvm",
  visibility = ["//visibility:public"],
)
