cc_library(
    name = "messenger",
    hdrs = ["messenger.hpp"],
    srcs = ["messenger.cpp"],
    deps = [
        "//:topology",
        "//:logger",
        "//:type_traits",
        "@com_github_gflags_gflags//:gflags",
    ],
    strip_include_prefix = "//src/messenger",
    include_prefix = "cvm",
    visibility = ["//visibility:public"],
)
