load("@rules_hdl//verilog:providers.bzl", "verilog_library")

cc_library(
    name = "messenger",
    srcs = ["messenger_dpi.cpp"],
    hdrs = ["messenger.hpp"],
    deps = [
        "@cvm//:topology",
    ],
    strip_include_prefix = "//src/messenger",
    include_prefix = "cvm",
    visibility = ["//visibility:public"],
)

verilog_library(
    name = "messenger_sv",
    srcs = ["cvm_messenger.sv"],
    visibility = ["//:__pkg__"],
)
