cc_library(
    name = "remote_procedure_call",
    deps = [
        "//:topology",
        "//:logger",
        "//:type_traits",
    ],
    srcs = ["rpc.cpp"],
    hdrs = ["rpc.hpp"],
    include_prefix = "cvm",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "remote_procedure_call_string",
    deps = [
        "//:topology",
        "//:logger",
    ],
    hdrs = ["rpc_string.hpp"],
    include_prefix = "cvm",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "remote_procedure_call_types",
    deps = [
        "//:topology",
        "//:logger",
    ],
    hdrs = ["rpc_types.hpp"],
    include_prefix = "cvm",
    visibility = ["//visibility:public"],
)
