load("@rules_hdl//verilog:providers.bzl", "verilog_library")
load("@rules_hdl//verilog:build_defs.bzl", "verilog_flist")
load("@rules_verilator//verilator:defs.bzl", "verilator_cc_library")

verilog_library(
    name = "logger_test_sv",
    srcs = ["logger_test.sv"],
)

verilog_flist(
    name = "logger_test.f",
    srcs = [":logger_test_sv"],
)

verilator_cc_library(
    name  = "logger_test_veri_lib",
    mtop  = "logger_test",
    vopts = ["--assert"],
    flist = "logger_test.f",
)

cc_test(
    name = "logger_test",
    size = "small",
    srcs = ["logger_test.cpp"],
    deps = [
        "//:logger",
        ":logger_test_veri_lib",
        "@com_google_googletest//:gtest_main",
    ],
    linkopts = ["-lz"],
)

