load("//:defs.bzl", "topology_gen")

topology_gen(
    name = "topology",
    srcs = ["topology.yml"],
)

cc_library(
    name = "sim_stubs",
    srcs = ["sim_stubs.cpp"],
    alwayslink = True,
    linkstatic = True,
)

cc_test(
    name = "topology_test",
    size = "small",
    srcs = ["topology_test.cpp"],
    linkstatic = True,
    deps = [
        ":topology",
        ":sim_stubs",
        "//:topology",
        "@com_google_googletest//:gtest_main",
    ],
)
