cc_library(
    name = "bitmanip",
    hdrs = ["bitmanip.hpp"],
    strip_include_prefix = "//include",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "messenger",
    hdrs = ["messenger.hpp"],
    strip_include_prefix = "//include",
    deps = ["@boost//:signals2"],
    visibility = ["//visibility:public"],
)
