load("@rules_verilator//verilator/internal:versions.bzl", verilator_version = "DEFAULT_VERSION")
load("//test:test.bzl", "linkopts")

cc_test(
    name = "rpc_types_test",
    size = "small",
    srcs = ["test.cpp"],
    deps = [
        "//src/remote_procedure_call:remote_procedure_call_types",
        "//:messenger",
        "@com_google_googletest//:gtest_main",
        "@verilator_v{}//:libverilator".format(verilator_version),
    ],
    linkopts = linkopts,
)