load(@cvm_pypi//:requirements.bzl", requirement")

cc_library(
  name = "topology",
  hdrs = ["topology.hpp"],
  visibility = ["//visibility:public"],
)

py_binary(
  name = "topology_gen",
  srcs = ["topology_gen.py"],
  deps = [
      requirement("Mako"),
      requirement("anytree"),
  ],
  data = glob(["templates/template.*"]),
  visibility = ["//visibility:public"],
)
